### ISSUE TITLE
Missing restaurants

### ISSUE THREAD

**Issue by schifano** [RISCfuture/ranked#2]
Restaurants of importance to me that are missing:

- Thai House
- La Mexicana
- Noodles
- Ft Jesse Cafe

**Comment by RISCfuture** [comment]
wow I didn't even notice this

**Comment by RISCfuture** [comment]
OK, I've added those four restaurants to the list. Couple of notes:

* Any previous result permalinks you have are now invalid. The test will have to be retaken.
* Because there are now 20 restaurants in the stack, 120 choices must be made to get a complete ranking.

http://r4nked.herokuapp.com/stacks/1
